from datetime import datetime
from models.db import products_col

products = [
    {"name": "Health Tracker 01", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 140.0, "image_url": "https://m.media-amazon.com/images/I/6171hDoxDbL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 02", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 145.0, "image_url": "https://m.media-amazon.com/images/I/71oJxdvyJ7L._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 03", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 150.0, "image_url": "https://m.media-amazon.com/images/I/814nAVofKwL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 04", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 155.0, "image_url": "https://m.media-amazon.com/images/I/71RIIaIMIML._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 05", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 160.0, "image_url": "https://m.media-amazon.com/images/I/61-vRq2ulOL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 06", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 165.0, "image_url": "https://m.media-amazon.com/images/I/61835CcjceL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 07", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 170.0, "image_url": "https://m.media-amazon.com/images/I/61MnFLjUA2L._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 08", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 175.0, "image_url": "https://m.media-amazon.com/images/I/710tB9vW2EL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 09", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 180.0, "image_url": "https://m.media-amazon.com/images/I/61Oy10E2IjL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 10", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 185.0, "image_url": "https://m.media-amazon.com/images/I/611s1CWplNL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 11", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 190.0, "image_url": "https://m.media-amazon.com/images/I/71qHWfeKocL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 12", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 195.0, "image_url": "https://m.media-amazon.com/images/I/417QEZ6QMlL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 13", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 200.0, "image_url": "https://m.media-amazon.com/images/I/81yDbbIiqBL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 14", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 205.0, "image_url": "https://m.media-amazon.com/images/I/61NdER7NwbL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Health Tracker 15", "brand": "Generic", "category": "Smart Watches", "subcategory": "Health Trackers", "tags": ["wearable", "health"], "rent_per_day": 210.0, "image_url": "https://m.media-amazon.com/images/I/61JCGjRVDmL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 01", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 120.0, "image_url": "https://m.media-amazon.com/images/I/61hK5QTdINL._AC_SR360,240_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 02", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 125.0, "image_url": "https://m.media-amazon.com/images/I/61IbvlnyyWL._AC_SR360,240_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 03", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 130.0, "image_url": "https://m.media-amazon.com/images/I/61bz4UNNcKL._AC_SR360,240_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 04", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 135.0, "image_url": "https://m.media-amazon.com/images/I/71HyzMqzzPL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 05", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 140.0, "image_url": "https://m.media-amazon.com/images/I/7190wwDOFxL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 06", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 145.0, "image_url": "https://m.media-amazon.com/images/I/81bEiPe3eWL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 07", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 150.0, "image_url": "https://m.media-amazon.com/images/I/41abF4vT-OL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 08", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 155.0, "image_url": "https://m.media-amazon.com/images/I/41zJEjObXwL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 09", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 160.0, "image_url": "https://m.media-amazon.com/images/I/514cBZZxi3L._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 10", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 165.0, "image_url": "https://m.media-amazon.com/images/I/61OT4f9kNqL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 11", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 170.0, "image_url": "https://m.media-amazon.com/images/I/61UIJp+pf5L._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 12", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 175.0, "image_url": "https://m.media-amazon.com/images/I/5111qTmNcTL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 13", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 180.0, "image_url": "https://m.media-amazon.com/images/I/41nWGlulecL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 14", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 185.0, "image_url": "https://m.media-amazon.com/images/I/71sGEWFWkxL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 15", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 190.0, "image_url": "https://m.media-amazon.com/images/I/51Q74o0dcYL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Fitness Band 16", "brand": "Generic", "category": "Smart Watches", "subcategory": "Fitness Bands", "tags": ["wearable", "fitness"], "rent_per_day": 195.0, "image_url": "https://m.media-amazon.com/images/I/61rcney+ghL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 01", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 200.0, "image_url": "https://m.media-amazon.com/images/I/613-2feQg9L._AC_SX416_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 02", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 210.0, "image_url": "https://m.media-amazon.com/images/I/61xSTnSOkuL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 03", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 220.0, "image_url": "https://m.media-amazon.com/images/I/71gdP7CfeiL._AC_SX416_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 04", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 230.0, "image_url": "https://m.media-amazon.com/images/I/61IKOhOH9LL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 05", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 240.0, "image_url": "https://m.media-amazon.com/images/I/61Famx7xQwL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 06", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 250.0, "image_url": "https://m.media-amazon.com/images/I/61rmkmqD5VL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 07", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 260.0, "image_url": "https://m.media-amazon.com/images/I/61-vRq2ulOL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 08", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 270.0, "image_url": "https://m.media-amazon.com/images/I/71rjlGEi+1L._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 09", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 280.0, "image_url": "https://m.media-amazon.com/images/I/81pTNhZHaYL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 10", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 290.0, "image_url": "https://images.unsplash.com/photo-1660844817855-3ecc7ef21f12?w=600&auto=format&fit=crop&q=60", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 11", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 300.0, "image_url": "https://images.unsplash.com/photo-1579721840641-7d0e67f1204e?w=600&auto=format&fit=crop&q=60", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 12", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 310.0, "image_url": "https://images.unsplash.com/photo-1669480380743-f76990b9bc44?w=600&auto=format&fit=crop&q=60", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 13", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 320.0, "image_url": "https://images.unsplash.com/photo-1668069225941-37356a72faac?w=600&auto=format&fit=crop&q=60", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 14", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 330.0, "image_url": "https://images.unsplash.com/photo-1736417670848-a2b516cb9aa3?w=600&auto=format&fit=crop&q=60", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 15", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 340.0, "image_url": "https://images.unsplash.com/photo-1693728910775-52d12398d2fb?w=600&auto=format&fit=crop&q=60", "available": True, "created_at": datetime.utcnow()},
    {"name": "Smart Watch 16", "brand": "Generic", "category": "Smart Watches", "subcategory": "Smart Watches", "tags": ["wearable", "smartwatch"], "rent_per_day": 350.0, "image_url": "https://images.unsplash.com/photo-1665860455418-017fa50d29bc?w=600&auto=format&fit=crop&q=60", "available": True, "created_at": datetime.utcnow()},
]

def run():
    added = 0
    for p in products:
        res = products_col.update_one({"name": p["name"]}, {"$setOnInsert": p}, upsert=True)
        if res.upserted_id:
            added += 1
    print(f"Added {added} new Smart Watches items." if added else "No new Smart Watches items added.")

if __name__ == "__main__":
    run()
