"""Insert Keyboards & Mouse products into the DB (Laptops -> Keyboards & Mouse)
Run: python add_keyboards_mouse.py
"""
from datetime import datetime
from models.db import products_col

products = [
    {
        "name": "Logitech MX Keys Wireless Keyboard",
        "brand": "Logitech",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 90.0,
        "image_url": "https://tse2.mm.bing.net/th/id/OIP.kivE7razcSy25CNyuQw4DgHaHa?pid=Api&P=0&h=180",
        "short_description": "Premium wireless keyboard with smart illumination.",
        "description": "Comfortable low-profile keys, smart backlighting, multi-device pairing.",
        "specs": {"connectivity": "Bluetooth/USB", "layout": "Full-size"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Logitech G502 HERO Gaming Mouse",
        "brand": "Logitech",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 80.0,
        "image_url": "https://tse1.mm.bing.net/th/id/OIP.08kKHUPZ9vDNwbJtnfAw_QHaEa?pid=Api&P=0&h=180",
        "short_description": "High-performance gaming mouse with adjustable weights.",
        "description": "11 programmable buttons, HERO sensor, customizable weight system.",
        "specs": {"dpi": "100-25600", "buttons": 11},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Corsair K70 RGB Mechanical Keyboard",
        "brand": "Corsair",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 100.0,
        "image_url": "https://tse4.mm.bing.net/th/id/OIP.63tmIuNwLRV_3rWv0MKTZwHaEl?pid=Api&P=0&h=180",
        "short_description": "Mechanical keyboard with Cherry MX switches.",
        "description": "Durable aluminum frame, per-key RGB lighting, media controls.",
        "specs": {"switch": "Cherry MX", "layout": "Full-size"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Razer Huntsman Elite Keyboard",
        "brand": "Razer",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 110.0,
        "image_url": "https://tse1.mm.bing.net/th/id/OIP.zEG4wzTg5bAB8GOqDECfoAHaE-?pid=Api&P=0&h=180",
        "short_description": "Opto-mechanical switches for ultra-fast actuation.",
        "description": "Ergonomic wrist rest, RGB lighting, media wheel.",
        "specs": {"switch": "Opto-mechanical", "layout": "Full-size"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Redragon K552 Kumara Compact Keyboard",
        "brand": "Redragon",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 60.0,
        "image_url": "https://tse4.mm.bing.net/th/id/OIP.FUkHymLfw68zZRoaeKkrvQHaFC?pid=Api&P=0&h=180",
        "short_description": "Compact mechanical keyboard for gaming and typing.",
        "description": "Durable, compact tenkeyless design, RGB backlight.",
        "specs": {"layout": "TKL", "switch": "Mechanical"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Dell KM117 Wireless Keyboard and Mouse Combo",
        "brand": "Dell",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 55.0,
        "image_url": "https://m.media-amazon.com/images/I/61wl+lg06XL._AC_UY327_FMwebp_QL65_.jpg",
        "short_description": "Reliable wireless keyboard and mouse combo.",
        "description": "Slim keyboard and ambidextrous optical mouse, plug-and-play.",
        "specs": {"connectivity": "2.4GHz USB"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "HP Pavilion Gaming Mouse 300",
        "brand": "HP",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 50.0,
        "image_url": "https://m.media-amazon.com/images/I/71IwgDD8KxL._AC_UL480_FMwebp_QL65_.jpg",
        "short_description": "Ergonomic gaming mouse with adjustable DPI.",
        "description": "RGB lighting, textured grip, multiple DPI levels.",
        "specs": {"dpi": "800-6400"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "SteelSeries Apex 3 Keyboard",
        "brand": "SteelSeries",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 70.0,
        "image_url": "https://m.media-amazon.com/images/I/71yVlPZv4YL._AC_UY327_FMwebp_QL65_.jpg",
        "short_description": "Whisper-quiet gaming keyboard with RGB.",
        "description": "IP32 water-resistant, durable keys, customizable RGB.",
        "specs": {"layout": "Full-size"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Logitech G305 Lightspeed Wireless Mouse",
        "brand": "Logitech",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 65.0,
        "image_url": "https://m.media-amazon.com/images/I/41bX3o-ZHqL._SY300_SX300_QL70_FMwebp_.jpg",
        "short_description": "Lightweight wireless gaming mouse with HERO sensor.",
        "description": "Ultra-lightweight, long battery life, accurate sensor.",
        "specs": {"dpi": "200-12000"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Razer DeathAdder V2",
        "brand": "Razer",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 85.0,
        "image_url": "https://m.media-amazon.com/images/I/61A-HAy-VSL._AC_UY327_FMwebp_QL65_.jpg",
        "short_description": "Classic ergonomic gaming mouse with optical switches.",
        "description": "High-precision sensor, comfortable grip for long sessions.",
        "specs": {"dpi": "100-20000"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Glorious Model O Gaming Mouse",
        "brand": "Glorious",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 75.0,
        "image_url": "https://m.media-amazon.com/images/I/71pDI91QISL._AC_UY327_FMwebp_QL65_.jpg",
        "short_description": "Ultra-light honeycomb gaming mouse.",
        "description": "Flexible cable, low weight, high-accuracy sensor.",
        "specs": {"dpi": "400-12000"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Keychron K2 Wireless Mechanical Keyboard",
        "brand": "Keychron",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 95.0,
        "image_url": "https://images.unsplash.com/photo-1637243218672-d338945efdf7?w=600",
        "short_description": "Compact 75% mechanical keyboard with Bluetooth.",
        "description": "Hot-swappable options, RGB backlight, multi-device pairing.",
        "specs": {"layout": "75%", "connectivity": "Bluetooth/USB-C"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Logitech Combo MK120 Keyboard & Mouse",
        "brand": "Logitech",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 45.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1661628680845-39b71e9be303?w=600",
        "short_description": "Affordable wired keyboard and mouse combo.",
        "description": "Reliable wired combo for everyday use.",
        "specs": {"connectivity": "USB"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Microsoft Surface Precision Mouse",
        "brand": "Microsoft",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 120.0,
        "image_url": "https://images.unsplash.com/photo-1622988464597-bb65ec55abca?w=600",
        "short_description": "High-precision mouse for creators and professionals.",
        "description": "Smooth tracking, multi-device support, ergonomic design.",
        "specs": {"connectivity": "Bluetooth/USB"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Apple Magic Keyboard",
        "brand": "Apple",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 150.0,
        "image_url": "https://images.unsplash.com/photo-1616832362542-295a8648a351?w=600",
        "short_description": "Slim wireless keyboard for Mac users.",
        "description": "Rechargeable, low-profile scissor switches, compact design.",
        "specs": {"connectivity": "Bluetooth"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Corsair K55 RGB Pro Keyboard",
        "brand": "Corsair",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 70.0,
        "image_url": "https://m.media-amazon.com/images/I/61broXFs0VL._AC_UY327_FMwebp_QL65_.jpg",
        "short_description": "Membrane gaming keyboard with RGB and macro keys.",
        "description": "Quiet membrane switches, dedicated macro keys, RGB.",
        "specs": {"layout": "Full-size"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
    {
        "name": "Logitech G Pro Wireless Mouse",
        "brand": "Logitech",
        "category": "Laptops",
        "subcategory": "Keyboards & Mouse",
        "rent_per_day": 140.0,
        "image_url": "https://tse4.mm.bing.net/th/id/OIP.mGCM6NWay7Emj-26nJ8TmgHaE8?pid=Api&P=0&h=180",
        "short_description": "Top-tier wireless esports mouse.",
        "description": "Ambidextrous design, HERO sensor, ultra-lightweight.",
        "specs": {"dpi": "100-25600"},
        "available": True,
        "created_at": datetime.utcnow(),
        "display_group": "laptops_keyboards_mouse_2025",
    },
]

inserted = []
for p in products:
    q = {"name": p["name"], "category": p["category"], "subcategory": p["subcategory"]}
    existing = products_col.find_one(q)
    if existing:
        print(f"Exists: {p['name']} (skipping)")
    else:
        res = products_col.insert_one(p)
        inserted.append(str(res.inserted_id))
        print(f"Inserted: {p['name']} -> {res.inserted_id}")

print('\nInserted IDs:')
for i in inserted:
    print(' -', i)
