"""Insert Mobile Accessories products into the DB (Mobiles -> Mobile Accessories)
Run: python add_mobile_accessories.py
"""
from datetime import datetime
from models.db import products_col

products = [
    {"name": "Flexible Clip Mobile Stand", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 20.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/p/j/i/clip-flexible-mobile-stand-360-degree-rotation-heavy-duty-clamp-original-imah9fvhaxarnpq3.jpeg?q=70", "short_description": "Flexible clip mobile stand with 360° rotation.", "description": "Heavy-duty clamp and flexible arm for secure mounting.", "specs": {"material": "Aluminum/Plastic"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Suction Cup Wall Stand", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 18.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/y/d/x/suction-cup-multi-purpose-mobile-charging-wall-stand-plastic-original-imagn46zz9zufgkb.jpeg?q=70", "short_description": "Suction cup wall charging stand.", "description": "Easy mount for charging on walls and smooth surfaces.", "specs": {"mount": "Suction"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Portronics Universal Mobile Holder", "brand": "Portronics", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 22.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/kgwld3k0/mobile-holder/b/m/w/por-122-modesk-universal-mobile-holder-black-portronics-original-imafxfb2ztabrxqp.jpeg?q=70", "short_description": "Universal mobile holder for desks.", "description": "Stable base and adjustable angle for comfortable viewing.", "specs": {"type": "Desk"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Bike Phone Holder", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 25.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/4/5/6/stand-bike-phone-aluminium-bicycle-motorcycle-adjustable-anti-original-imagz247z8jrs6ct.jpeg?q=70", "short_description": "Aluminium adjustable bike phone holder.", "description": "Durable clamp, anti-shock mount for bikes and motorcycles.", "specs": {"mount": "Bike"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "MUHAAS Phone Stand", "brand": "MUHAAS", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 16.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/i/q/p/stand-004-muhaas-no-original-imahgmmzfraeh7fr.jpeg?q=70", "short_description": "Simple desktop phone stand.", "description": "Lightweight and portable for everyday use.", "specs": {"type": "Desk"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Wall Mount Charging Stand (Pack of 4)", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 30.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/a/f/i/stand-pack-of-4-phone-charging-stand-wall-mount-mobile-holder-original-imahey89hkyck5xh.jpeg?q=70", "short_description": "Pack of wall charging mounts.", "description": "Convenient multi-unit wall mounts for charging stations.", "specs": {"pack": 4}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Adjustable Table Mobile Holder", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 20.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/l3rmzrk0/mobile-holder/6/c/m/stand-mobile-holder-stand-for-table-mobile-holder-adjustable-original-imagetkzvkqrtecu.jpeg?q=70", "short_description": "Adjustable table mobile holder.", "description": "360° rotation and tilt for optimal viewing angles.", "specs": {"rotation": "360deg"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Magnetic Suction Mobile Holder", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 24.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/7/y/c/stand-magnetic-vacuum-suction-mobile-holder-360-rotatable-original-imaheyn5msgghhfu.jpeg?q=70", "short_description": "Magnetic vacuum suction holder.", "description": "Strong magnetic hold with 360° rotation.", "specs": {"mount": "Magnetic"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Clip Wall/Tablet Mount", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 26.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/3/0/6/clip-s-200-wall-mount-tablet-holder-secure-adjustable-for-all-original-imahaq3sssjmdrgz.jpeg?q=70", "short_description": "Secure clip wall/tablet mount.", "description": "Heavy-duty clip for tablets and phones.", "specs": {"type": "Clip"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Sticky Pad Universal Holder", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 15.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/c/c/b/sticky-pad-wall-charger-hook-universal-cellphone-hanging-stand-original-imagzb3ygnkxawra.jpeg?q=70", "short_description": "Sticky pad universal holder.", "description": "Reusable sticky pad for quick mounting.", "specs": {"type": "Sticky"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Desktop Mobile & Tablet Stand", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 28.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/mobile-holder/d/h/y/stand-desktop-mobile-tablet-holder-360-rotating-adjustable-original-imagyez2shdxt78p.jpeg?q=70", "short_description": "Desktop stand for mobile & tablet.", "description": "Adjustable and sturdy desktop stand for devices.", "specs": {"rotation": "360deg"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
    {"name": "Foldable Aluminium Tablet Stand", "brand": "Generic", "category": "Mobiles", "subcategory": "Mobile Accessories", "rent_per_day": 32.0, "image_url": "https://rukminim2.flixcart.com/image/612/612/xif0q/laptop-stand/o/9/s/350-aluminium-tablet-stand-rotating-base-foldable-compatible-for-original-imahfcr8zcaugjhz.jpeg?q=70", "short_description": "Foldable aluminium tablet stand.", "description": "Portable and sturdy stand for tablets and laptops.", "specs": {"material": "Aluminium"}, "available": True, "created_at": datetime.utcnow(), "display_group": "mobiles_mobile_accessories_2025"},
]

inserted = []
for p in products:
    q = {"name": p["name"], "category": p["category"], "subcategory": p["subcategory"]}
    existing = products_col.find_one(q)
    if existing:
        print(f"Exists: {p['name']} (skipping)")
    else:
        res = products_col.insert_one(p)
        inserted.append(str(res.inserted_id))
        print(f"Inserted: {p['name']} -> {res.inserted_id}")

print('\nInserted IDs:')
for i in inserted:
    print(' -', i)
