from datetime import datetime
from models.db import products_col

new_products = [
    # Handheld Console Products
    {
        "name": "Handheld Console 01",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 300.0,
        "image_url": "https://m.media-amazon.com/images/I/61bHJTtWr2L._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 02",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 320.0,
        "image_url": "https://m.media-amazon.com/images/I/613g3KfYteL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 03",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 340.0,
        "image_url": "https://m.media-amazon.com/images/I/612rii4NfGL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 04",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 360.0,
        "image_url": "https://m.media-amazon.com/images/I/61QZbqAUvKL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 05",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 380.0,
        "image_url": "https://m.media-amazon.com/images/I/51+BVgUZdYL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 06",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 400.0,
        "image_url": "https://m.media-amazon.com/images/I/71wKSz1I4zL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 07",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 420.0,
        "image_url": "https://m.media-amazon.com/images/I/511gYPs6+QL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 08",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 440.0,
        "image_url": "https://m.media-amazon.com/images/I/81qBl-7NAkL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 09",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 460.0,
        "image_url": "https://m.media-amazon.com/images/I/61NlUFroGHL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 10",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 480.0,
        "image_url": "https://m.media-amazon.com/images/I/618F1AzUacL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 11",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 500.0,
        "image_url": "https://m.media-amazon.com/images/I/71KqXO9svkL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 12",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 520.0,
        "image_url": "https://m.media-amazon.com/images/I/61xp1UbvXtL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 13",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 540.0,
        "image_url": "https://m.media-amazon.com/images/I/41vF2GZHraL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 14",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 560.0,
        "image_url": "https://m.media-amazon.com/images/I/51W7rcR559L._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Handheld Console 15",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Console",
        "tags": ["gaming", "console", "handheld"],
        "rent_per_day": 580.0,
        "image_url": "https://m.media-amazon.com/images/I/61ifKljoGwL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    # Controllers Products
    {
        "name": "Gaming Controller 01",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 100.0,
        "image_url": "https://images.unsplash.com/photo-1712390978993-faa4edb44d48?w=600&auto=format&fit=crop&q=60",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 02",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 120.0,
        "image_url": "https://images.unsplash.com/photo-1677985635176-2bae3b3464f0?w=600&auto=format&fit=crop&q=60",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 03",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 140.0,
        "image_url": "https://images.unsplash.com/photo-1731834452451-f9a68be378ae?w=600&auto=format&fit=crop&q=60",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 04",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 160.0,
        "image_url": "https://images.unsplash.com/photo-1580327332925-a10e6cb11baa?w=600&auto=format&fit=crop&q=60",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 05",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 180.0,
        "image_url": "https://images.unsplash.com/photo-1703868671298-b1d776d486f7?w=600&auto=format&fit=crop&q=60",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 06",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 200.0,
        "image_url": "https://images.unsplash.com/photo-1562177613-f2669eea104f?w=600&auto=format&fit=crop&q=60",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 07",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 220.0,
        "image_url": "https://images.unsplash.com/photo-1761164034378-573f87613427?w=600&auto=format&fit=crop&q=60",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 08",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 240.0,
        "image_url": "https://m.media-amazon.com/images/I/71Mj4xd0YML._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 09",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 260.0,
        "image_url": "https://m.media-amazon.com/images/I/51qUiQxtQqL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 10",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 280.0,
        "image_url": "https://m.media-amazon.com/images/I/61FXFhr1r7L._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 11",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 300.0,
        "image_url": "https://m.media-amazon.com/images/I/5193+FaPk2L._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 12",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 320.0,
        "image_url": "https://m.media-amazon.com/images/I/61+-9CC-IsL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 13",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 340.0,
        "image_url": "https://m.media-amazon.com/images/I/718AG-9zAOL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 14",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 360.0,
        "image_url": "https://m.media-amazon.com/images/I/81jUXmVgrfL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Gaming Controller 15",
        "brand": "Generic",
        "category": "Gaming Consoles",
        "subcategory": "Controllers",
        "tags": ["gaming", "console", "controller"],
        "rent_per_day": 380.0,
        "image_url": "https://m.media-amazon.com/images/I/51iefaxmqeL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    }
]

def run():
    print("Checking for new products to add...")
    count = 0
    for p in new_products:
        res = products_col.update_one(
            {"name": p["name"]},
            {"$setOnInsert": p},
            upsert=True
        )
        if res.upserted_id:
            count += 1
    if count > 0:
        print(f"Added {count} new products.")
    else:
        print("No new products added (duplicates checked).")

if __name__ == "__main__":
    run()
