from datetime import datetime
from models.db import products_col

new_products = [
    # Earbuds
    {
        "name": "Noise Buds VS102",
        "brand": "Noise",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "noise"],
        "rent_per_day": 80.0,
        "image_url": "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&auto=format&fit=crop&q=60",
        "description": "Noise Buds VS102 — stylish flybird design with 50H playtime.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Boat Airdopes 141",
        "brand": "Boat",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "boat"],
        "rent_per_day": 70.0,
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=60",
        "description": "Boat Airdopes 141 — 42H playback, beast mode for gaming.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Realme Buds Air 3",
        "brand": "Realme",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "realme"],
        "rent_per_day": 120.0,
        "image_url": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=600&auto=format&fit=crop&q=60",
        "description": "Realme Buds Air 3 — 42dB active noise cancellation.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL Tune 130NC",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "jbl"],
        "rent_per_day": 150.0,
        "image_url": "https://images.unsplash.com/photo-1722439667098-f32094e3b1d4?w=600&auto=format&fit=crop&q=60",
        "description": "JBL Tune 130NC — pure bass sound, active noise cancelling.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "OnePlus Nord Buds",
        "brand": "OnePlus",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "oneplus"],
        "rent_per_day": 90.0,
        "image_url": "https://images.unsplash.com/photo-1632200004922-bc18602c79fc?w=600&auto=format&fit=crop&q=60",
        "description": "OnePlus Nord Buds — 12.4mm titanium drivers, 30H playtime.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Samsung Galaxy Buds2",
        "brand": "Samsung",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "samsung"],
        "rent_per_day": 180.0,
        "image_url": "https://images.unsplash.com/photo-1574920162043-b872873f19c8?w=600&auto=format&fit=crop&q=60",
        "description": "Samsung Galaxy Buds2 — balanced sound, active noise cancellation.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Apple AirPods Pro 2",
        "brand": "Apple",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "apple"],
        "rent_per_day": 350.0,
        "image_url": "https://images.unsplash.com/photo-1655560378428-7605bda51749?w=600&auto=format&fit=crop&q=60",
        "description": "Apple AirPods Pro 2 — richer audio, next-level active noise cancellation.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony WF-C500",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "sony"],
        "rent_per_day": 130.0,
        "image_url": "https://images.unsplash.com/photo-1667178173387-7e0cb51c0b4f?w=600&auto=format&fit=crop&q=60",
        "description": "Sony WF-C500 — truly wireless earbuds with 20H battery.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Oppo Enco Air 2",
        "brand": "Oppo",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "oppo"],
        "rent_per_day": 85.0,
        "image_url": "https://media.istockphoto.com/id/1254998855/photo/airpod-with-black-background.webp",
        "description": "Oppo Enco Air 2 — 13.4mm composite titanized diaphragm driver.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Boult Audio AirBass",
        "brand": "Boult",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "boult"],
        "rent_per_day": 60.0,
        "image_url": "https://images.unsplash.com/photo-1617350142147-7403b8fb9889?w=600&auto=format&fit=crop&q=60",
        "description": "Boult Audio AirBass — environmental noise cancellation.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Mivi DuoPods F40",
        "brand": "Mivi",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "mivi"],
        "rent_per_day": 50.0,
        "image_url": "https://images.unsplash.com/photo-1655804446276-7699884b469b?w=600&auto=format&fit=crop&q=60",
        "description": "Mivi DuoPods F40 — 50H playtime, made in India.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Truke Buds BTG2",
        "brand": "Truke",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "truke"],
        "rent_per_day": 55.0,
        "image_url": "https://m.media-amazon.com/images/I/61oPWuyuT2L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Truke Buds BTG2 — gaming earbuds with 60ms latency.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PTron Bassbuds Duo",
        "brand": "PTron",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "ptron"],
        "rent_per_day": 45.0,
        "image_url": "https://m.media-amazon.com/images/I/61bcY1YYXoL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "PTron Bassbuds Duo — immersive stereo sound, touch control.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Wings Phantom 200",
        "brand": "Wings",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "wings"],
        "rent_per_day": 65.0,
        "image_url": "https://m.media-amazon.com/images/I/5136i2M3bPL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Wings Phantom 200 — gaming true wireless earbuds with LED lights.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Noise Buds Connect",
        "brand": "Noise",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["headphones", "earbuds", "wireless", "noise"],
        "rent_per_day": 75.0,
        "image_url": "https://m.media-amazon.com/images/I/71rlmEZ6cjL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Noise Buds Connect — quad mic with ENC, 50H playtime.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    # Wired Headphones
    {
        "name": "Sony MDR-ZX110",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "sony"],
        "rent_per_day": 50.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1677838847545-1ebd2eefb7a0?w=600&auto=format&fit=crop&q=60",
        "description": "Sony MDR-ZX110 — on-ear stereo headphones, foldable design.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL C50HI",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "jbl"],
        "rent_per_day": 40.0,
        "image_url": "https://images.unsplash.com/photo-1742570922875-e5a60e950307?w=600&auto=format&fit=crop&q=60",
        "description": "JBL C50HI — in-ear headphones with mic, dynamic bass.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Boat BassHeads 900",
        "brand": "Boat",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "boat"],
        "rent_per_day": 60.0,
        "image_url": "https://m.media-amazon.com/images/I/61iSV4o+X-L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Boat BassHeads 900 — wired on-ear headphones with mic.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sennheiser HD 206",
        "brand": "Sennheiser",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "sennheiser"],
        "rent_per_day": 90.0,
        "image_url": "https://m.media-amazon.com/images/I/51QTyJ107KL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sennheiser HD 206 — lightweight over-ear headphones, powerful sound.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Audio-Technica ATH-M20x",
        "brand": "Audio-Technica",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "audio-technica"],
        "rent_per_day": 150.0,
        "image_url": "https://m.media-amazon.com/images/I/511rSZltO-L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Audio-Technica ATH-M20x — professional monitor headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL Tune 500",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "jbl"],
        "rent_per_day": 80.0,
        "image_url": "https://m.media-amazon.com/images/I/61-XJRAVoPL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "JBL Tune 500 — wired on-ear headphones with pure bass.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony MDR-XB450AP",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "sony"],
        "rent_per_day": 100.0,
        "image_url": "https://m.media-amazon.com/images/I/61HBpQuLjVL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sony MDR-XB450AP — extra bass headphones with mic.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Logitech H111",
        "brand": "Logitech",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "logitech"],
        "rent_per_day": 40.0,
        "image_url": "https://m.media-amazon.com/images/I/51GGwjwSr0L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Logitech H111 — multi-device stereo headset.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Zebronics Zeb-Thunder",
        "brand": "Zebronics",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "zebronics"],
        "rent_per_day": 50.0,
        "image_url": "https://m.media-amazon.com/images/I/61D6kMS3KwL._AC_UL960_FMwebp_QL65_.jpg",
        "description": "Zebronics Zeb-Thunder — wireless BT headphone with wired option.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "OneOdio Pro-10",
        "brand": "OneOdio",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "oneodio"],
        "rent_per_day": 110.0,
        "image_url": "https://m.media-amazon.com/images/I/71D1EB5iDzL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "OneOdio Pro-10 — adapter-free closed back headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Panasonic RP-HT161",
        "brand": "Panasonic",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "panasonic"],
        "rent_per_day": 60.0,
        "image_url": "https://m.media-amazon.com/images/I/31NvbqTDPsS._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Panasonic RP-HT161 — full-sized lightweight long-cord headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Behringer HPM1000",
        "brand": "Behringer",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "behringer"],
        "rent_per_day": 70.0,
        "image_url": "https://m.media-amazon.com/images/I/51HN96FHhHL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Behringer HPM1000 — multi-purpose headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Philips SHP9600",
        "brand": "Philips",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "philips"],
        "rent_per_day": 200.0,
        "image_url": "https://m.media-amazon.com/images/I/61PlUpGmAYL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Philips SHP9600 — open-back over-ear headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "AKG K52",
        "brand": "AKG",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "akg"],
        "rent_per_day": 130.0,
        "image_url": "https://m.media-amazon.com/images/I/71llQ7h6qFL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "AKG K52 — closed-back studio headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Beyerdynamic DT 770",
        "brand": "Beyerdynamic",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "beyerdynamic"],
        "rent_per_day": 250.0,
        "image_url": "https://m.media-amazon.com/images/I/71dsjhhIpbL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Beyerdynamic DT 770 — studio reference headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
]

def run():
    print("Checking for new headphones to add...")
    count = 0
    for p in new_products:
        # Upsert based on name to avoid duplicates but ensure latest data
        res = products_col.update_one(
            {"name": p["name"]},
            {"$setOnInsert": p},
            upsert=True
        )
        if res.upserted_id:
            count += 1
    if count > 0:
        print(f"Added {count} new products.")
    else:
        print("No new products added.")

if __name__ == "__main__":
    run()
