from datetime import datetime
from models.db import products_col

new_products = [
    # --- Wired Headphones ---
    {
        "name": "Sony MDR-ZX110",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "sony"],
        "rent_per_day": 50.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1677838847545-1ebd2eefb7a0?w=600&auto=format&fit=crop&q=60",
        "description": "Sony MDR-ZX110 — on-ear stereo headphones, foldable design.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL C50HI",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "jbl"],
        "rent_per_day": 40.0,
        "image_url": "https://images.unsplash.com/photo-1742570922875-e5a60e950307?w=600&auto=format&fit=crop&q=60",
        "description": "JBL C50HI — in-ear headphones with mic, dynamic bass.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Boat BassHeads 900",
        "brand": "Boat",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "boat"],
        "rent_per_day": 60.0,
        "image_url": "https://m.media-amazon.com/images/I/61iSV4o+X-L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Boat BassHeads 900 — wired on-ear headphones with mic.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sennheiser HD 206",
        "brand": "Sennheiser",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "sennheiser"],
        "rent_per_day": 90.0,
        "image_url": "https://m.media-amazon.com/images/I/51QTyJ107KL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sennheiser HD 206 — lightweight over-ear headphones, powerful sound.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Audio-Technica ATH-M20x",
        "brand": "Audio-Technica",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "audio-technica"],
        "rent_per_day": 150.0,
        "image_url": "https://m.media-amazon.com/images/I/511rSZltO-L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Audio-Technica ATH-M20x — professional monitor headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL Tune 500",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "jbl"],
        "rent_per_day": 80.0,
        "image_url": "https://m.media-amazon.com/images/I/61-XJRAVoPL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "JBL Tune 500 — wired on-ear headphones with pure bass.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony MDR-XB450AP",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "sony"],
        "rent_per_day": 100.0,
        "image_url": "https://m.media-amazon.com/images/I/61HBpQuLjVL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sony MDR-XB450AP — extra bass headphones with mic.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Logitech H111",
        "brand": "Logitech",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "logitech"],
        "rent_per_day": 40.0,
        "image_url": "https://m.media-amazon.com/images/I/51GGwjwSr0L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Logitech H111 — multi-device stereo headset.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Zebronics Zeb-Thunder",
        "brand": "Zebronics",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "zebronics"],
        "rent_per_day": 50.0,
        "image_url": "https://m.media-amazon.com/images/I/61D6kMS3KwL._AC_UL960_FMwebp_QL65_.jpg",
        "description": "Zebronics Zeb-Thunder — wireless BT headphone with wired option.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "OneOdio Pro-10",
        "brand": "OneOdio",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "oneodio"],
        "rent_per_day": 110.0,
        "image_url": "https://m.media-amazon.com/images/I/71D1EB5iDzL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "OneOdio Pro-10 — adapter-free closed back headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Panasonic RP-HT161",
        "brand": "Panasonic",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "panasonic"],
        "rent_per_day": 60.0,
        "image_url": "https://m.media-amazon.com/images/I/31NvbqTDPsS._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Panasonic RP-HT161 — full-sized lightweight long-cord headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Behringer HPM1000",
        "brand": "Behringer",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "behringer"],
        "rent_per_day": 70.0,
        "image_url": "https://m.media-amazon.com/images/I/51HN96FHhHL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Behringer HPM1000 — multi-purpose headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Philips SHP9600",
        "brand": "Philips",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "philips"],
        "rent_per_day": 200.0,
        "image_url": "https://m.media-amazon.com/images/I/61PlUpGmAYL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Philips SHP9600 — open-back over-ear headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "AKG K52",
        "brand": "AKG",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "akg"],
        "rent_per_day": 130.0,
        "image_url": "https://m.media-amazon.com/images/I/71llQ7h6qFL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "AKG K52 — closed-back studio headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Beyerdynamic DT 770",
        "brand": "Beyerdynamic",
        "category": "Headphones",
        "subcategory": "Wired Headphones",
        "tags": ["headphones", "wired", "beyerdynamic"],
        "rent_per_day": 250.0,
        "image_url": "https://m.media-amazon.com/images/I/71dsjhhIpbL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Beyerdynamic DT 770 — studio reference headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },

    # --- Bluetooth Speakers ---
    {
        "name": "JBL Flip 6",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "jbl"],
        "rent_per_day": 120.0,
        "image_url": "https://m.media-amazon.com/images/I/81y8cmMBngL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "JBL Flip 6 — portable bluetooth speaker with powerful sound.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Boat Stone 1000",
        "brand": "Boat",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "boat"],
        "rent_per_day": 90.0,
        "image_url": "https://m.media-amazon.com/images/I/51lAg4itSAL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Boat Stone 1000 — 14W powerful stereo sound.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony SRS-XB13",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "sony"],
        "rent_per_day": 100.0,
        "image_url": "https://m.media-amazon.com/images/I/71Gn7eWoLUL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sony SRS-XB13 — extra bass portable wireless speaker.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Marshall Emberton",
        "brand": "Marshall",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "marshall"],
        "rent_per_day": 250.0,
        "image_url": "https://m.media-amazon.com/images/I/6134Xh9JpgL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Marshall Emberton — compact portable speaker with loud sound.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Ultimate Ears Wonderboom 3",
        "brand": "Ultimate Ears",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "ultimate ears"],
        "rent_per_day": 150.0,
        "image_url": "https://m.media-amazon.com/images/I/418SigfmUnL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Ultimate Ears Wonderboom 3 — big bass 360-degree sound.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Bose SoundLink Flex",
        "brand": "Bose",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "bose"],
        "rent_per_day": 300.0,
        "image_url": "https://m.media-amazon.com/images/I/71ur52HJ8cL._AC_UL480_FMwebp_QL65_.jpg",
        "description": "Bose SoundLink Flex — waterproof bluetooth speaker.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Tribit StormBox",
        "brand": "Tribit",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "tribit"],
        "rent_per_day": 130.0,
        "image_url": "https://m.media-amazon.com/images/I/81kvKTql0cL._AC_UL480_FMwebp_QL65_.jpg",
        "description": "Tribit StormBox — 360 sound wireless speaker.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Anker Soundcore 3",
        "brand": "Anker",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "anker"],
        "rent_per_day": 110.0,
        "image_url": "https://m.media-amazon.com/images/I/71-I9Bk8dgL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Anker Soundcore 3 — stereo sound with 24H playtime.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Mivi Roam 2",
        "brand": "Mivi",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "mivi"],
        "rent_per_day": 60.0,
        "image_url": "https://m.media-amazon.com/images/I/613LNL9foqL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Mivi Roam 2 — 5W wireless speaker with punchy bass.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Portronics SoundDrum",
        "brand": "Portronics",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "portronics"],
        "rent_per_day": 70.0,
        "image_url": "https://m.media-amazon.com/images/I/71ipFwOLapL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Portronics SoundDrum — 10W portable speaker.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Zebronics Zeb-County",
        "brand": "Zebronics",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "zebronics"],
        "rent_per_day": 50.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1677159499898-b061fb5bd2d7?w=600&auto=format&fit=crop&q=60",
        "description": "Zebronics Zeb-County — portable speaker with FM radio.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Infinity Fuze 100",
        "brand": "Infinity",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "infinity"],
        "rent_per_day": 80.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1728978926426-18fdb1d00e8a?w=600&auto=format&fit=crop&q=60",
        "description": "Infinity Fuze 100 — dual EQ deep bass speaker.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xiaomi Mi Portable",
        "brand": "Xiaomi",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "xiaomi"],
        "rent_per_day": 85.0,
        "image_url": "https://images.unsplash.com/photo-1547052178-7f2c5a20c332?w=600&auto=format&fit=crop&q=60",
        "description": "Xiaomi Mi Portable — 16W bluetooth speaker.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Realme Cobble",
        "brand": "Realme",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "realme"],
        "rent_per_day": 75.0,
        "image_url": "https://images.unsplash.com/photo-1687363251769-560d957b8847?w=600&auto=format&fit=crop&q=60",
        "description": "Realme Cobble — 5W bluetooth speaker with game mode.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Phillips BT50",
        "brand": "Phillips",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speakers", "bluetooth", "phillips"],
        "rent_per_day": 65.0,
        "image_url": "https://images.unsplash.com/photo-1565209559032-5a73935b73d7?w=600&auto=format&fit=crop&q=60",
        "description": "Phillips BT50 — compact wireless portable speaker.",
        "available": True,
        "created_at": datetime.utcnow(),
    },

    # --- Sound Bars ---
    {
        "name": "Sony HT-S20R",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "sony"],
        "rent_per_day": 200.0,
        "image_url": "https://m.media-amazon.com/images/I/71IG0Fhcu2L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sony HT-S20R — 5.1ch dolby digital soundbar.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL Cinema SB271",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "jbl"],
        "rent_per_day": 180.0,
        "image_url": "https://m.media-amazon.com/images/I/71-I9Bk8dgL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "JBL Cinema SB271 — 2.1 channel soundbar with subwoofer.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Boat Aavante Bar",
        "brand": "Boat",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "boat"],
        "rent_per_day": 150.0,
        "image_url": "https://m.media-amazon.com/images/I/71+Y1B4HaqL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Boat Aavante Bar — premium home theatre soundbar.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Samsung HW-T420",
        "brand": "Samsung",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "samsung"],
        "rent_per_day": 170.0,
        "image_url": "https://m.media-amazon.com/images/I/51SFh0i5HHL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Samsung HW-T420 — 2.1ch soundbar with powerful bass.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Zebronics Jukebar 9700",
        "brand": "Zebronics",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "zebronics"],
        "rent_per_day": 190.0,
        "image_url": "https://m.media-amazon.com/images/I/71Wrs49loGL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Zebronics Jukebar 9700 — dolby atmos soundbar.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Philips TAB8947",
        "brand": "Philips",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "philips"],
        "rent_per_day": 210.0,
        "image_url": "https://m.media-amazon.com/images/I/813Ru0LsF9L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Philips TAB8947 — 5.1.2ch soundbar with subwoofer.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Bose Smart Soundbar 600",
        "brand": "Bose",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "bose"],
        "rent_per_day": 350.0,
        "image_url": "https://m.media-amazon.com/images/I/81t+HbL-ESL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Bose Smart Soundbar 600 — dolby atmos and voice control.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Yamaha YAS-209",
        "brand": "Yamaha",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "yamaha"],
        "rent_per_day": 280.0,
        "image_url": "https://m.media-amazon.com/images/I/71X3yLZz3bL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Yamaha YAS-209 — sound bar with wireless subwoofer.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Polk Audio Signa S4",
        "brand": "Polk Audio",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "polk"],
        "rent_per_day": 260.0,
        "image_url": "https://m.media-amazon.com/images/I/81SVmY55KuL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Polk Audio Signa S4 — ultra-slim sound bar.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sonos Beam Gen 2",
        "brand": "Sonos",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "sonos"],
        "rent_per_day": 400.0,
        "image_url": "https://m.media-amazon.com/images/I/51TEhp-YXzL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sonos Beam Gen 2 — smart compact soundbar.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Blaupunkt SBA20",
        "brand": "Blaupunkt",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "blaupunkt"],
        "rent_per_day": 120.0,
        "image_url": "https://m.media-amazon.com/images/I/41GILiIfFVL._AC_UL480_FMwebp_QL65_.jpg",
        "description": "Blaupunkt SBA20 — 16W bluetooth soundbar.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Mivi Fort S100",
        "brand": "Mivi",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "mivi"],
        "rent_per_day": 140.0,
        "image_url": "https://m.media-amazon.com/images/I/81vpTj8V0CL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Mivi Fort S100 — 100W soundbar with subwoofer.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Portronics Pure Sound",
        "brand": "Portronics",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "portronics"],
        "rent_per_day": 130.0,
        "image_url": "https://m.media-amazon.com/images/I/716hdDsyT9L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Portronics Pure Sound — wired/wireless soundbar.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Govo GoSurround",
        "brand": "Govo",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "govo"],
        "rent_per_day": 160.0,
        "image_url": "https://m.media-amazon.com/images/I/71CZJlY5uQL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Govo GoSurround — 2.1 channel home theatre.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Motorola Amphisound",
        "brand": "Motorola",
        "category": "Headphones",
        "subcategory": "Sound Bars",
        "tags": ["speakers", "soundbar", "motorola"],
        "rent_per_day": 180.0,
        "image_url": "https://m.media-amazon.com/images/I/71eRAMvY25L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Motorola Amphisound — 150W soundbar with subwoofer.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
]

def run():
    print("Checking for new products to add...")
    count = 0
    for p in new_products:
        # Upsert based on name to avoid duplicates but ensure latest data
        res = products_col.update_one(
            {"name": p["name"]},
            {"$setOnInsert": p},
            upsert=True
        )
        if res.upserted_id:
            count += 1
    if count > 0:
        print(f"Added {count} new products.")
    else:
        print("No new products added (duplicates checked).")

if __name__ == "__main__":
    run()
