from datetime import datetime
from models.db import products_col

products = [
    # Chargers (16)
    {"name": "Charger 01", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 60.0, "image_url": "https://m.media-amazon.com/images/I/61fx+coIftL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 02", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 62.0, "image_url": "https://m.media-amazon.com/images/I/612GqDniteL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 03", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 64.0, "image_url": "https://m.media-amazon.com/images/I/41AHEO-ofUL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 04", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 66.0, "image_url": "https://m.media-amazon.com/images/I/61+CW3ppfXL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 05", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 68.0, "image_url": "https://m.media-amazon.com/images/I/41nEN7g6-pL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 06", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 70.0, "image_url": "https://m.media-amazon.com/images/I/61eXyBrp1LL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 07", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 72.0, "image_url": "https://m.media-amazon.com/images/I/71fR0dCQ0XL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 08", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 74.0, "image_url": "https://m.media-amazon.com/images/I/41u976e5AZL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 09", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 76.0, "image_url": "https://m.media-amazon.com/images/I/61yynb2fDIL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 10", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 78.0, "image_url": "https://m.media-amazon.com/images/I/71OPy1mcyvL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 11", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 80.0, "image_url": "https://m.media-amazon.com/images/I/61KD6btQzcL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 12", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 82.0, "image_url": "https://m.media-amazon.com/images/I/61ZDw9x2LdL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 13", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 84.0, "image_url": "https://m.media-amazon.com/images/I/615YNgpC7eL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 14", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 86.0, "image_url": "https://m.media-amazon.com/images/I/51+KFUOerAL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 15", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 88.0, "image_url": "https://m.media-amazon.com/images/I/51pV0R56zWL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Charger 16", "brand": "Generic", "category": "Accessories", "subcategory": "Chargers", "tags": ["accessories", "charger"], "rent_per_day": 90.0, "image_url": "https://m.media-amazon.com/images/I/51u6D64MNVL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    # Power Banks (15)
    {"name": "Power Bank 01", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 70.0, "image_url": "https://m.media-amazon.com/images/I/61bRRxkSdlL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 02", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 75.0, "image_url": "https://m.media-amazon.com/images/I/61nNdhS88QL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 03", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 80.0, "image_url": "https://m.media-amazon.com/images/I/61HgzHGMBBL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 04", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 85.0, "image_url": "https://m.media-amazon.com/images/I/71TUiV0TyiL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 05", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 90.0, "image_url": "https://m.media-amazon.com/images/I/41vBAaU8clL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 06", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 95.0, "image_url": "https://m.media-amazon.com/images/I/61VtNg3YsPL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 07", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 100.0, "image_url": "https://m.media-amazon.com/images/I/61rYwwPPxVL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 08", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 105.0, "image_url": "https://m.media-amazon.com/images/I/51wVOEHrpmL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 09", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 110.0, "image_url": "https://m.media-amazon.com/images/I/61ielYy4Y3L._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 10", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 115.0, "image_url": "https://m.media-amazon.com/images/I/61VH3KVV+JL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 11", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 120.0, "image_url": "https://m.media-amazon.com/images/I/61hXQYjKroL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 12", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 125.0, "image_url": "https://m.media-amazon.com/images/I/71zqv+i9eTL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 13", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 130.0, "image_url": "https://m.media-amazon.com/images/I/61X9YXFwC0L._AC_SX644_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 14", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 135.0, "image_url": "https://m.media-amazon.com/images/I/61V4py-0ndL._AC_SX644_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Power Bank 15", "brand": "Generic", "category": "Accessories", "subcategory": "Power Banks", "tags": ["accessories", "powerbank"], "rent_per_day": 140.0, "image_url": "https://m.media-amazon.com/images/I/61bRRxkSdlL._AC_UL480_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    # Cables (15)
    {"name": "Cable 01", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 30.0, "image_url": "https://m.media-amazon.com/images/I/6176iruQKcL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 02", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 32.0, "image_url": "https://m.media-amazon.com/images/I/7100MyxcglL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 03", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 34.0, "image_url": "https://m.media-amazon.com/images/I/61W8xeZTwxL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 04", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 36.0, "image_url": "https://m.media-amazon.com/images/I/61TAAu1LrqL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 05", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 38.0, "image_url": "https://m.media-amazon.com/images/I/71MhtZF5NWL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 06", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 40.0, "image_url": "https://m.media-amazon.com/images/I/61pS1rIm8QL._AC_SX644_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 07", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 42.0, "image_url": "https://m.media-amazon.com/images/I/71ICmfK203L._AC_SX644_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 08", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 44.0, "image_url": "https://m.media-amazon.com/images/I/71-qZIbecTL._AC_SX644_CB1169409_QL70_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 09", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 46.0, "image_url": "https://m.media-amazon.com/images/I/7100MyxcglL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 10", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 48.0, "image_url": "https://m.media-amazon.com/images/I/51xBoyVLWwL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 11", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 50.0, "image_url": "https://m.media-amazon.com/images/I/61qsIhub23L._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 12", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 52.0, "image_url": "https://m.media-amazon.com/images/I/514uClj3DfL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 13", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 54.0, "image_url": "https://m.media-amazon.com/images/I/61jzBtqSF-L._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 14", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 56.0, "image_url": "https://m.media-amazon.com/images/I/81uOlhjsOQL._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
    {"name": "Cable 15", "brand": "Generic", "category": "Accessories", "subcategory": "Cables", "tags": ["accessories", "cable"], "rent_per_day": 58.0, "image_url": "https://m.media-amazon.com/images/I/61w9SDINq6L._AC_UY327_FMwebp_QL65_.jpg", "available": True, "created_at": datetime.utcnow()},
]

def run():
    add_count = 0
    for p in products:
        res = products_col.update_one({"name": p["name"]}, {"$setOnInsert": p}, upsert=True)
        if res.upserted_id:
            add_count += 1
    print(f"Added {add_count} Accessories items." if add_count else "No new Accessories items added.")

if __name__ == "__main__":
    run()
