from datetime import datetime
from models.db import products_col


sample_products = [
    {
        "name": "Apple iPhone 14",
        "brand": "Apple",
        "category": "Mobiles",
        "subcategory": "Smartphones",
        "tags": ["smartphones", "mobile", "ios"],
        "rent_per_day": 1200.0,
        "image_url": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Samsung Galaxy S23",
        "brand": "Samsung",
        "category": "Mobiles",
        "subcategory": "Smartphones",
        "tags": ["android", "smartphones"],
        "rent_per_day": 1100.0,
        "image_url": "https://images.unsplash.com/photo-1610552773715-4b0a2b8b3b5d?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony WH-1000XM5",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["audio", "headphones", "wireless"],
        "rent_per_day": 350.0,
        "image_url": "https://images.unsplash.com/photo-1518444021894-5ec2a6a2a4b3?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS R10",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["camera", "mirrorless"],
        "rent_per_day": 900.0,
        "image_url": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Apple MacBook Air M2",
        "brand": "Apple",
        "category": "Laptops",
        "subcategory": "Laptops",
        "tags": ["laptop", "macbook"],
        "rent_per_day": 1800.0,
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nintendo Switch OLED",
        "brand": "Nintendo",
        "category": "Gaming Consoles",
        "subcategory": "Handheld Consoles",
        "tags": ["gaming", "console"],
        "rent_per_day": 900.0,
        "image_url": "https://images.unsplash.com/photo-1606813903298-6b91d8f0d6dc?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Fitbit Versa 3",
        "brand": "Fitbit",
        "category": "Smart Watches",
        "subcategory": "Smart Watches",
        "tags": ["wearable", "fitness"],
        "rent_per_day": 150.0,
        "image_url": "https://images.unsplash.com/photo-1523475496153-3d6cc8be5c2a?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Anker PowerCore 20000",
        "brand": "Anker",
        "category": "Accessories",
        "subcategory": "Power Banks",
        "tags": ["charger", "powerbank"],
        "rent_per_day": 80.0,
        "image_url": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    # Additional 20 products
    {
        "name": "Google Pixel 7 Pro",
        "brand": "Google",
        "category": "Mobiles",
        "subcategory": "Smartphones",
        "tags": ["android", "smartphone"],
        "rent_per_day": 1050.0,
        "image_url": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "OnePlus 11",
        "brand": "OnePlus",
        "category": "Mobiles",
        "subcategory": "Smartphones",
        "tags": ["android", "smartphone"],
        "rent_per_day": 900.0,
        "image_url": "https://images.unsplash.com/photo-1592286927505-1def25e4cda1?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xiaomi 13 Pro",
        "brand": "Xiaomi",
        "category": "Mobiles",
        "subcategory": "Smartphones",
        "tags": ["android", "smartphone"],
        "rent_per_day": 800.0,
        "image_url": "https://images.unsplash.com/photo-1511240170023-6812883a0a20?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Bose QuietComfort 45",
        "brand": "Bose",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["audio", "headphones", "wireless"],
        "rent_per_day": 400.0,
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL Flip 6",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Bluetooth Speakers",
        "tags": ["speaker", "bluetooth"],
        "rent_per_day": 200.0,
        "image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon Z6II",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["camera", "mirrorless"],
        "rent_per_day": 1200.0,
        "image_url": "https://images.unsplash.com/photo-1606933248051-5ce3b9b1e02f?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony Alpha A7IV",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["camera", "mirrorless"],
        "rent_per_day": 1400.0,
        "image_url": "https://images.unsplash.com/photo-1606933248051-5ce3b9b1e02f?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "GoPro Hero 11",
        "brand": "GoPro",
        "category": "Cameras",
        "subcategory": "Action Cameras",
        "tags": ["camera", "action"],
        "rent_per_day": 400.0,
        "image_url": "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Dell XPS 13",
        "brand": "Dell",
        "category": "Laptops",
        "subcategory": "Laptops",
        "tags": ["laptop", "ultrabook"],
        "rent_per_day": 1600.0,
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "HP Pavilion 15",
        "brand": "HP",
        "category": "Laptops",
        "subcategory": "Laptops",
        "tags": ["laptop"],
        "rent_per_day": 1400.0,
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Lenovo ThinkPad X1",
        "brand": "Lenovo",
        "category": "Laptops",
        "subcategory": "Laptops",
        "tags": ["laptop", "business"],
        "rent_per_day": 1500.0,
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation 5",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "Home Consoles",
        "tags": ["gaming", "console"],
        "rent_per_day": 1100.0,
        "image_url": "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Series X",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Home Consoles",
        "tags": ["gaming", "console"],
        "rent_per_day": 1100.0,
        "image_url": "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Apple Watch Series 8",
        "brand": "Apple",
        "category": "Smart Watches",
        "subcategory": "Smart Watches",
        "tags": ["wearable", "smartwatch"],
        "rent_per_day": 250.0,
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Garmin Epix",
        "brand": "Garmin",
        "category": "Smart Watches",
        "subcategory": "Smart Watches",
        "tags": ["wearable", "fitness"],
        "rent_per_day": 200.0,
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Samsung Galaxy Buds Pro",
        "brand": "Samsung",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["earbuds", "wireless"],
        "rent_per_day": 150.0,
        "image_url": "https://images.unsplash.com/photo-1545127398-14699f92334b?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "AirPods Pro",
        "brand": "Apple",
        "category": "Headphones",
        "subcategory": "Earbuds",
        "tags": ["earbuds", "wireless"],
        "rent_per_day": 200.0,
        "image_url": "https://images.unsplash.com/photo-1606841837239-c5a1a8a07af7?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xiaomi Power Bank 30000",
        "brand": "Xiaomi",
        "category": "Accessories",
        "subcategory": "Power Banks",
        "tags": ["charger", "powerbank"],
        "rent_per_day": 100.0,
        "image_url": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "USB-C Hub Pro",
        "brand": "Anker",
        "category": "Accessories",
        "subcategory": "Cables & Adapters",
        "tags": ["cables", "adapter"],
        "rent_per_day": 50.0,
        "image_url": "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "HDMI 2.1 Cable 3m",
        "brand": "Belkin",
        "category": "Accessories",
        "subcategory": "Cables & Adapters",
        "tags": ["cables", "hdmi"],
        "rent_per_day": 30.0,
        "image_url": "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=1200&q=80&auto=format&fit=crop",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    # DSLR Cameras (15 items)
    {
        "name": "Canon EOS 90D",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 1400.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1673349178635-39b654f84401?w=600&auto=format&fit=crop&q=60",
        "description": "Canon EOS 90D DSLR — high-resolution APS-C sensor, great for photography projects.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D7500",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 1350.0,
        "image_url": "https://images.unsplash.com/photo-1593449651424-adb56e5001aa?w=600&auto=format&fit=crop&q=60",
        "description": "Nikon D7500 — reliable DSLR with excellent low-light performance.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony Alpha DSLR",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "sony"],
        "rent_per_day": 1500.0,
        "image_url": "https://images.unsplash.com/photo-1621958054700-7af166501105?w=600&auto=format&fit=crop&q=60",
        "description": "Sony Alpha DSLR — versatile performance for photo and video.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS 80D",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 1250.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1673349178750-b35929b751b1?w=600&auto=format&fit=crop&q=60",
        "description": "Canon EOS 80D — reliable performer for enthusiasts.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D5600",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 1100.0,
        "image_url": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=60",
        "description": "Nikon D5600 — lightweight DSLR with great image quality.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS 6D Mark II",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 1700.0,
        "image_url": "https://images.unsplash.com/photo-1721310334462-66f07f8e3b1d?w=600&auto=format&fit=crop&q=60",
        "description": "Full-frame Canon DSLR, excellent for professional shoots.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D850",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 2200.0,
        "image_url": "https://m.media-amazon.com/images/I/71iKNJ6rVIL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Nikon D850 — high-resolution full-frame DSLR for demanding photographers.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS R (DSLR-style mirrorless listed as DSLR for this catalog)",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 2000.0,
        "image_url": "https://m.media-amazon.com/images/I/813X74rfb1L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "High-performance Canon camera suited to DSLR workflows.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D7200",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 1200.0,
        "image_url": "https://m.media-amazon.com/images/I/71Js9C22AyL._AC_UL480_FMwebp_QL65_.jpg",
        "description": "Nikon D7200 — solid mid-range DSLR for photo projects.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS Rebel T7i",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 950.0,
        "image_url": "https://m.media-amazon.com/images/I/71u7HJItZoL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Entry-level DSLR ideal for learning photography.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Vintage DSLR Pack",
        "brand": "Various",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "vintage"],
        "rent_per_day": 600.0,
        "image_url": "https://tse1.mm.bing.net/th/id/OIP.zt5597xs-4_k1Ug1rIh_BgHaEK",
        "description": "Collection of refurbished/vintage DSLR bodies and primes.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS 5D Mark IV",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 2300.0,
        "image_url": "https://tse1.mm.bing.net/th/id/OIP.WIxD1TcdoOV4oTKwas5D6AHaEo",
        "description": "Professional full-frame DSLR, ideal for studio and events.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D500",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 1900.0,
        "image_url": "https://tse3.mm.bing.net/th/id/OIP.EJVpvTR6oGfoimQQZ3VeUQHaEr",
        "description": "Nikon D500 — fast-action DSLR for wildlife and sports.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS 7D Mark II",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 1450.0,
        "image_url": "https://tse2.mm.bing.net/th/id/OIP.j6LEoBhqASpWQv1YYlgbtAHaEo",
        "description": "Canon 7D Mark II — robust DSLR for action photography.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D3300",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 800.0,
        "image_url": "https://tse3.mm.bing.net/th/id/OIP.eamnG8hpgwvNFak5M2zSlQHaHa",
        "description": "Affordable DSLR for beginners and hobbyists.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    # Webcams (15 items)
    {
        "name": "Logitech C920",
        "brand": "Logitech",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "logitech"],
        "rent_per_day": 180.0,
        "image_url": "https://m.media-amazon.com/images/I/51gTkS5fHVL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Full HD 1080p webcam with built-in mic and USB connection.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "HP HD Webcam",
        "brand": "HP",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "hp"],
        "rent_per_day": 150.0,
        "image_url": "https://m.media-amazon.com/images/I/61nTmIUB0LL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "HD webcam with noise-reducing mic and plug-and-play USB.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Dell Pro Webcam",
        "brand": "Dell",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "dell"],
        "rent_per_day": 170.0,
        "image_url": "https://m.media-amazon.com/images/I/71qnZFqFM9L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "1080p webcam with wide-angle lens and USB-C adapter.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Razer Kiyo",
        "brand": "Razer",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "razer"],
        "rent_per_day": 220.0,
        "image_url": "https://m.media-amazon.com/images/I/61q7GuSnqDL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Full HD webcam with ring light for consistent lighting.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Anker PowerConf C300",
        "brand": "Anker",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "anker"],
        "rent_per_day": 160.0,
        "image_url": "https://m.media-amazon.com/images/I/71Lcx3Y2HdL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "1080p webcam with auto-framing and dual microphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Microsoft LifeCam",
        "brand": "Microsoft",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "microsoft"],
        "rent_per_day": 140.0,
        "image_url": "https://m.media-amazon.com/images/I/51zB4pCl8gL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "720p/1080p webcam with noise-cancelling mic and tripod mount.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Logitech Brio 4K",
        "brand": "Logitech",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "logitech"],
        "rent_per_day": 450.0,
        "image_url": "https://m.media-amazon.com/images/I/612aK9LfsSL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "4K UHD webcam with HDR and high-quality stereo mic.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Creative Live! Cam",
        "brand": "Creative",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "creative"],
        "rent_per_day": 130.0,
        "image_url": "https://images.unsplash.com/photo-1622750342107-4b60e2704157",
        "description": "HD webcam with built-in mic and flexible mount.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Logitech StreamCam",
        "brand": "Logitech",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "logitech"],
        "rent_per_day": 300.0,
        "image_url": "https://images.unsplash.com/photo-1650017069174-341a368606a0",
        "description": "1080p 60fps webcam optimized for streaming and content creation.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "AUSDOM AW615",
        "brand": "AUSDOM",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "ausdom"],
        "rent_per_day": 120.0,
        "image_url": "https://images.unsplash.com/photo-1670278458296-00ff8a63141e",
        "description": "Wide-angle Full HD webcam with built-in mic.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Hikvision USB Webcam",
        "brand": "Hikvision",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "hikvision"],
        "rent_per_day": 210.0,
        "image_url": "https://images.unsplash.com/photo-1726127461372-547b9ffa4236",
        "description": "HD webcam with low-light enhancement and mic.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Logitech C505e",
        "brand": "Logitech",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "logitech"],
        "rent_per_day": 160.0,
        "image_url": "https://images.unsplash.com/photo-1728971568218-03a7f87c9e99",
        "description": "1080p webcam with noise-reducing mic and universal mount.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Microsoft Modern Webcam",
        "brand": "Microsoft",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "microsoft"],
        "rent_per_day": 240.0,
        "image_url": "https://images.unsplash.com/photo-1572534178961-a81b24c29b9d",
        "description": "Full HD webcam with auto-framing and dual microphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "AverMedia Live Streamer",
        "brand": "AverMedia",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "avermedia"],
        "rent_per_day": 280.0,
        "image_url": "https://images.unsplash.com/photo-1636902512853-d9bc4b14a72a",
        "description": "High-quality webcam for streamers with good low-light performance.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Logitech C925e",
        "brand": "Logitech",
        "category": "Cameras",
        "subcategory": "Webcams",
        "tags": ["webcam", "logitech"],
        "rent_per_day": 200.0,
        "image_url": "https://m.media-amazon.com/images/I/71Gtq-HuQVL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Business-class 1080p webcam with auto light correction and stereo mic.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    # Refurbished Mobiles (15 items)
    {
        "name": "Refurbished iPhone 12",
        "brand": "Apple",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "iphone", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 800.0,
        "image_url": "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/r/i/5/-original-imah6svfd2rccdyb.jpeg?q=70",
        "description": "Good condition refurbished iPhone 12. Fully tested and functional.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished OnePlus 9",
        "brand": "OnePlus",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "oneplus", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 450.0,
        "image_url": "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile-refurbished-fk/q/w/s/-original-imaha52t7jtgvnbf.jpeg?q=70",
        "description": "Refurbished OnePlus 9 with clean IMEI and working battery.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Pixel 4a",
        "brand": "Google",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "pixel", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 300.0,
        "image_url": "https://images.unsplash.com/photo-1643162601564-34c164be6ba0?w=600&auto=format&fit=crop&q=60",
        "description": "Compact refurbished Pixel 4a, ideal for everyday use.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Galaxy S20",
        "brand": "Samsung",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "samsung", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 500.0,
        "image_url": "https://m.media-amazon.com/images/I/61FcXMhjr8L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Refurbished Galaxy S20 with good battery health.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Redmi Note 10",
        "brand": "Xiaomi",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "xiaomi", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 180.0,
        "image_url": "https://m.media-amazon.com/images/I/616Ge16GLFL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Affordable refurbished Redmi Note 10, suitable for daily tasks.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Moto G Power",
        "brand": "Motorola",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "motorola", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 160.0,
        "image_url": "https://m.media-amazon.com/images/I/718HzJbvY1L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Long-battery refurbished Moto G Power for extended use.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Nokia 7.2",
        "brand": "Nokia",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "nokia", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 140.0,
        "image_url": "https://m.media-amazon.com/images/I/71LIzk0Uj8L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Reliable refurbished Nokia with solid build quality.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Oppo F19",
        "brand": "Oppo",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "oppo", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 200.0,
        "image_url": "https://m.media-amazon.com/images/I/61FX8qveBNL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Clean refurbished Oppo F19, ready to rent.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Vivo V21",
        "brand": "Vivo",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "vivo", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 220.0,
        "image_url": "https://m.media-amazon.com/images/I/81AyOlAxwuL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Stylish refurbished Vivo V21 with good camera performance.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Realme 8",
        "brand": "Realme",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "realme", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 170.0,
        "image_url": "https://m.media-amazon.com/images/I/51ox0MGozFL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Good refurbished Realme 8 for everyday multimedia use.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished LG Velvet",
        "brand": "LG",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "lg", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 260.0,
        "image_url": "https://m.media-amazon.com/images/I/61Gl4860bcL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Premium-feel refurbished LG Velvet with AMOLED display.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Sony Xperia 10",
        "brand": "Sony",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "sony", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 240.0,
        "image_url": "https://m.media-amazon.com/images/I/6153Y0HG6xL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Refurbished Sony Xperia with clean Android build.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished HTC Desire",
        "brand": "HTC",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "htc", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 120.0,
        "image_url": "https://m.media-amazon.com/images/I/41cO4f11LZL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Affordable refurbished HTC device in working condition.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Alcatel Go",
        "brand": "Alcatel",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "alcatel", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 90.0,
        "image_url": "https://m.media-amazon.com/images/I/51CwFq4kPsL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Simple refurbished Alcatel phone, great for basic use.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Refurbished Blackberry Classic",
        "brand": "Blackberry",
        "category": "Mobiles",
        "subcategory": "Refurbished Mobiles",
        "tags": ["refurbished", "blackberry", "mobile"],
        "condition": "Refurbished",
        "rent_per_day": 110.0,
        "image_url": "https://m.media-amazon.com/images/I/712y5oYW5CL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Classic-style refurbished Blackberry for focused productivity.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    # Mirrorless Cameras (15 items)
    {
        "name": "Sony Alpha 7 IV",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sony"],
        "rent_per_day": 2000.0,
        "image_url": "https://images.unsplash.com/photo-1630565046172-a45b756acf0f?w=600&auto=format&fit=crop&q=60",
        "description": "Sony Alpha 7 IV — professional full-frame mirrorless for photography and video.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS R50",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "canon"],
        "rent_per_day": 1600.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1667538961167-2f0ab7a5046e?w=600&auto=format&fit=crop&q=60",
        "description": "Canon EOS R50 — versatile mirrorless with great autofocus.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Fujifilm X-T5",
        "brand": "Fujifilm",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "fujifilm"],
        "rent_per_day": 1800.0,
        "image_url": "https://images.unsplash.com/photo-1611952987537-c1c9c1f4f6a2?w=600&auto=format&fit=crop&q=60",
        "description": "Fujifilm X-T5 — compact mirrorless with excellent color science.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon Z9",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "nikon"],
        "rent_per_day": 2400.0,
        "image_url": "https://images.unsplash.com/photo-1651464654814-3031b30d8a99?w=600&auto=format&fit=crop&q=60",
        "description": "Nikon Z9 — professional full-frame with advanced 8K capabilities.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony ZV-E10",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sony"],
        "rent_per_day": 1200.0,
        "image_url": "https://images.unsplash.com/photo-1731424359375-0ceee30ef813?w=600&auto=format&fit=crop&q=60",
        "description": "Sony ZV-E10 — content creator mirrorless with flip screen.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Panasonic Lumix S5II",
        "brand": "Panasonic",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "panasonic"],
        "rent_per_day": 1700.0,
        "image_url": "https://images.unsplash.com/photo-1697208386304-7129844c5df1?w=600&auto=format&fit=crop&q=60",
        "description": "Panasonic Lumix S5II — affordable full-frame mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Olympus OM System",
        "brand": "Olympus",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "olympus"],
        "rent_per_day": 1100.0,
        "image_url": "https://images.unsplash.com/photo-1723472281045-e926a5ee9929?w=600&auto=format&fit=crop&q=60",
        "description": "Olympus mirrorless — compact APS-C with great stabilization.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sigma fp",
        "brand": "Sigma",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sigma"],
        "rent_per_day": 1400.0,
        "image_url": "https://m.media-amazon.com/images/I/61vuQLaJAdL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sigma fp — compact full-frame mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony Alpha 6700",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sony"],
        "rent_per_day": 1350.0,
        "image_url": "https://m.media-amazon.com/images/I/71gB-5SVNUL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sony Alpha 6700 — APS-C mirrorless with excellent autofocus.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS R6",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "canon"],
        "rent_per_day": 1900.0,
        "image_url": "https://m.media-amazon.com/images/I/61xMohRsKGL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Canon EOS R6 — pro-level full-frame mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon Z50II",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "nikon"],
        "rent_per_day": 1150.0,
        "image_url": "https://m.media-amazon.com/images/I/71veESr7laL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Nikon Z50II — compact APS-C mirrorless for enthusiasts.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Leica SL2",
        "brand": "Leica",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "leica"],
        "rent_per_day": 3200.0,
        "image_url": "https://m.media-amazon.com/images/I/71JurfqudIL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Leica SL2 — premium full-frame mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Hasselblad X1D II 50C",
        "brand": "Hasselblad",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "hasselblad"],
        "rent_per_day": 4000.0,
        "image_url": "https://m.media-amazon.com/images/I/61nKqwfoZBL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Hasselblad X1D II — high-end medium format mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony ZV-E1",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sony"],
        "rent_per_day": 2100.0,
        "image_url": "https://rukminim2.flixcart.com/image/312/312/ktlu9ow0/dslr-camera/r/y/j/alpha-zv-e10-24-2-megapixel-with-interchangeable-lens-aps-c-original-imag6wxxhxrv9htc.jpeg?q=70",
        "description": "Sony ZV-E1 — full-frame content creator camera.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Blackmagic Pocket Cinema Camera 4K",
        "brand": "Blackmagic",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "blackmagic"],
        "rent_per_day": 2500.0,
        "image_url": "https://rukminim2.flixcart.com/image/312/312/xif0q/camera/1/y/b/na-blackmagic-pocket-cinema-camera-4k-mirrorless-blackmagic-original-imahf7zberyhaatm.jpeg?q=70",
        "description": "Blackmagic Pocket Cinema 4K — professional video mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    # Wireless Headphones (15 items)
    {
        "name": "Sony WH-CH520",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "sony"],
        "rent_per_day": 150.0,
        "image_url": "https://m.media-amazon.com/images/I/61ttOStDEqL._AC_SX416_CB1169409_QL70_.jpg",
        "description": "Sony WH-CH520 — lightweight wireless headphones with long battery life.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL Tune 510BT",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "jbl"],
        "rent_per_day": 120.0,
        "image_url": "https://m.media-amazon.com/images/I/61L4SkS7w2L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "JBL Tune 510BT — pure bass sound and multipoint connection.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Boat Rockerz 450",
        "brand": "Boat",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "boat"],
        "rent_per_day": 80.0,
        "image_url": "https://m.media-amazon.com/images/I/61B5hIAmvdL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Boat Rockerz 450 — on-ear wireless headphones with lush audio.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sennheiser HD 350BT",
        "brand": "Sennheiser",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "sennheiser"],
        "rent_per_day": 200.0,
        "image_url": "https://m.media-amazon.com/images/I/51DSjZ8at1L._AC_UL960_FMwebp_QL65_.jpg",
        "description": "Sennheiser HD 350BT — superior wireless sound with deep dynamic bass.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Philips H4205",
        "brand": "Philips",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "philips"],
        "rent_per_day": 100.0,
        "image_url": "https://m.media-amazon.com/images/I/71quB2GTUKL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Philips H4205 — on-ear wireless headphones with bass boost button.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony WH-XB910N",
        "brand": "Sony",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "sony"],
        "rent_per_day": 300.0,
        "image_url": "https://m.media-amazon.com/images/I/61XvYOrqVeL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sony WH-XB910N — extra bass noise cancelling headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "JBL Tune 760NC",
        "brand": "JBL",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "jbl"],
        "rent_per_day": 250.0,
        "image_url": "https://m.media-amazon.com/images/I/61faDMBMdmL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "JBL Tune 760NC — active noise cancelling wireless over-ear headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Boat Nirvana 751",
        "brand": "Boat",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "boat"],
        "rent_per_day": 180.0,
        "image_url": "https://m.media-amazon.com/images/I/41jJ755MC+L._AC_UL849_FMwebp_QL65_.jpg",
        "description": "Boat Nirvana 751 — hybrid active noise cancellation.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Skullcandy Hesh Evo",
        "brand": "Skullcandy",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "skullcandy"],
        "rent_per_day": 160.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1710962439403-a35fbc684b15?w=600&auto=format&fit=crop&q=60",
        "description": "Skullcandy Hesh Evo — wireless over-ear headphones with tile finding technology.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Marshall Major IV",
        "brand": "Marshall",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "marshall"],
        "rent_per_day": 400.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1677838847804-4054143fb91a?w=600&auto=format&fit=crop&q=60",
        "description": "Marshall Major IV — iconic on-ear headphones with 80+ hours of wireless playtime.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Audio-Technica ATH-M20xBT",
        "brand": "Audio-Technica",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "audio-technica"],
        "rent_per_day": 220.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1679913793289-d1ba3b9b0187?w=600&auto=format&fit=crop&q=60",
        "description": "Audio-Technica ATH-M20xBT — wireless over-ear headphones studio sound.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Soundcore Q30",
        "brand": "Soundcore",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "soundcore"],
        "rent_per_day": 190.0,
        "image_url": "https://images.unsplash.com/photo-1676315636995-a5d5df17b192?w=600&auto=format&fit=crop&q=60",
        "description": "Soundcore Q30 — hybrid active noise cancelling headphones with multiple modes.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Edifier W820NB",
        "brand": "Edifier",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "edifier"],
        "rent_per_day": 170.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1679913796054-fc4e44f35b40?w=600&auto=format&fit=crop&q=60",
        "description": "Edifier W820NB — hi-res audio wireless noise cancelling headphones.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "AKG Y500",
        "brand": "AKG",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "akg"],
        "rent_per_day": 210.0,
        "image_url": "https://images.unsplash.com/photo-1653919114056-640c16de7838?w=600&auto=format&fit=crop&q=60",
        "description": "AKG Y500 — on-ear wireless headphones with ambient aware technology.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Beats Solo3",
        "brand": "Beats",
        "category": "Headphones",
        "subcategory": "Wireless Headphones",
        "tags": ["headphones", "wireless", "beats"],
        "rent_per_day": 350.0,
        "image_url": "https://images.unsplash.com/photo-1760708368699-69cb9ed56f52?w=600&auto=format&fit=crop&q=60",
        "description": "Beats Solo3 — wireless on-ear headphones with Apple W1 chip.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 01",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 500.0,
        "image_url": "https://m.media-amazon.com/images/I/61LeN75i3HL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 02",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 520.0,
        "image_url": "https://m.media-amazon.com/images/I/61xL8bitZfL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 03",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 540.0,
        "image_url": "https://m.media-amazon.com/images/I/71daUUzFPML._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 04",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 560.0,
        "image_url": "https://m.media-amazon.com/images/I/4155O0pFDLL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 05",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 580.0,
        "image_url": "https://m.media-amazon.com/images/I/51vRD5ozYmL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 06",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 600.0,
        "image_url": "https://m.media-amazon.com/images/I/5137WOLt5qL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 07",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 620.0,
        "image_url": "https://m.media-amazon.com/images/I/71jqUPp0hzL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 08",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 640.0,
        "image_url": "https://m.media-amazon.com/images/I/31wkagD6moL._AC_UY300_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 09",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 660.0,
        "image_url": "https://m.media-amazon.com/images/I/61duSh4ZP5L._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 10",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 680.0,
        "image_url": "https://m.media-amazon.com/images/I/71zJ6jh2OwL._AC_SX416_CB1169409_QL70_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 11",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 700.0,
        "image_url": "https://m.media-amazon.com/images/I/71ZQAV02kFL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 12",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 720.0,
        "image_url": "https://m.media-amazon.com/images/I/71-WhgqkzoL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 13",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 740.0,
        "image_url": "https://m.media-amazon.com/images/I/71jqUPp0hzL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 14",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 760.0,
        "image_url": "https://m.media-amazon.com/images/I/718uJTrO2gL._AC_UL960_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "PlayStation Console 15",
        "brand": "Sony",
        "category": "Gaming Consoles",
        "subcategory": "PlayStation",
        "tags": ["gaming", "console", "playstation"],
        "rent_per_day": 780.0,
        "image_url": "https://m.media-amazon.com/images/I/71S-vzJp2+L._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 01",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 500.0,
        "image_url": "https://m.media-amazon.com/images/I/71NBQ2a52CL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 02",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 520.0,
        "image_url": "https://m.media-amazon.com/images/I/61c0Ufa7IdL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 03",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 540.0,
        "image_url": "https://m.media-amazon.com/images/I/61ZbpSrtepL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 04",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 560.0,
        "image_url": "https://m.media-amazon.com/images/I/61Byaf6q2uL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 05",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 580.0,
        "image_url": "https://m.media-amazon.com/images/I/61LaPQVyx2L._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 06",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 600.0,
        "image_url": "https://m.media-amazon.com/images/I/81rcx2yWUOL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 07",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 620.0,
        "image_url": "https://m.media-amazon.com/images/I/61OMdRnmNSL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 08",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 640.0,
        "image_url": "https://m.media-amazon.com/images/I/51k9LDNgwSL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 09",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 660.0,
        "image_url": "https://m.media-amazon.com/images/I/71nbv9BhgyL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 10",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 680.0,
        "image_url": "https://m.media-amazon.com/images/I/51q4b52+loL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 11",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 700.0,
        "image_url": "https://m.media-amazon.com/images/I/71KoRdQ6I6L._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 12",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 720.0,
        "image_url": "https://m.media-amazon.com/images/I/61GUPPlwhwL._AC_UL480_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 13",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 740.0,
        "image_url": "https://m.media-amazon.com/images/I/61dA1spQFLL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 14",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 760.0,
        "image_url": "https://m.media-amazon.com/images/I/81V2IVlgzoL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Xbox Console 15",
        "brand": "Microsoft",
        "category": "Gaming Consoles",
        "subcategory": "Xbox",
        "tags": ["gaming", "console", "xbox"],
        "rent_per_day": 780.0,
        "image_url": "https://m.media-amazon.com/images/I/71WwZbxbAyL._AC_UY327_FMwebp_QL65_.jpg",
        "available": True,
        "created_at": datetime.utcnow(),
    },
]


def run():
    if products_col.count_documents({}) == 0:
        products_col.insert_many(sample_products)
        print(f"Inserted {len(sample_products)} products")
    else:
        # Check if we need to add missing products (simple check by name)
        print("Checking for new products to add...")
        count = 0
        for p in sample_products:
            # Upsert based on name to avoid duplicates but ensure latest data
            res = products_col.update_one(
                {"name": p["name"]},
                {"$setOnInsert": p},
                upsert=True
            )
            if res.upserted_id:
                count += 1
        if count > 0:
            print(f"Added {count} new products.")
        else:
            print("No new products added.")


if __name__ == "__main__":
    run()


