from datetime import datetime
import sys, os

# Ensure project root is on sys.path so relative imports like `models` resolve
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from models.db import products_col

DSLR_PRODUCTS = [
    {
        "name": "Canon EOS 90D",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 1400.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1673349178635-39b654f84401?w=600&auto=format&fit=crop&q=60",
        "description": "Canon EOS 90D DSLR — high-resolution APS-C sensor, great for photography projects.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D7500",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 1350.0,
        "image_url": "https://images.unsplash.com/photo-1593449651424-adb56e5001aa?w=600&auto=format&fit=crop&q=60",
        "description": "Nikon D7500 — reliable DSLR with excellent low-light performance.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony Alpha DSLR",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "sony"],
        "rent_per_day": 1500.0,
        "image_url": "https://images.unsplash.com/photo-1621958054700-7af166501105?w=600&auto=format&fit=crop&q=60",
        "description": "Sony Alpha DSLR — versatile performance for photo and video.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS 80D",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 1250.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1673349178750-b35929b751b1?w=600&auto=format&fit=crop&q=60",
        "description": "Canon EOS 80D — reliable performer for enthusiasts.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D5600",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 1100.0,
        "image_url": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=60",
        "description": "Nikon D5600 — lightweight DSLR with great image quality.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS 6D Mark II",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 1700.0,
        "image_url": "https://images.unsplash.com/photo-1721310334462-66f07f8e3b1d?w=600&auto=format&fit=crop&q=60",
        "description": "Full-frame Canon DSLR, excellent for professional shoots.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D850",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 2200.0,
        "image_url": "https://m.media-amazon.com/images/I/71iKNJ6rVIL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Nikon D850 — high-resolution full-frame DSLR for demanding photographers.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS R (DSLR-style mirrorless listed as DSLR for this catalog)",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 2000.0,
        "image_url": "https://m.media-amazon.com/images/I/813X74rfb1L._AC_UY327_FMwebp_QL65_.jpg",
        "description": "High-performance Canon camera suited to DSLR workflows.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D7200",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 1200.0,
        "image_url": "https://m.media-amazon.com/images/I/71Js9C22AyL._AC_UL480_FMwebp_QL65_.jpg",
        "description": "Nikon D7200 — solid mid-range DSLR for photo projects.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS Rebel T7i",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 950.0,
        "image_url": "https://m.media-amazon.com/images/I/71u7HJItZoL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Entry-level DSLR ideal for learning photography.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Vintage DSLR Pack",
        "brand": "Various",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "vintage"],
        "rent_per_day": 600.0,
        "image_url": "https://tse1.mm.bing.net/th/id/OIP.zt5597xs-4_k1Ug1rIh_BgHaEK",
        "description": "Collection of refurbished/vintage DSLR bodies and primes.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS 5D Mark IV",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 2300.0,
        "image_url": "https://tse1.mm.bing.net/th/id/OIP.WIxD1TcdoOV4oTKwas5D6AHaEo",
        "description": "Professional full-frame DSLR, ideal for studio and events.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D500",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 1900.0,
        "image_url": "https://tse3.mm.bing.net/th/id/OIP.EJVpvTR6oGfoimQQZ3VeUQHaEr",
        "description": "Nikon D500 — fast-action DSLR for wildlife and sports.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS 7D Mark II",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "canon"],
        "rent_per_day": 1450.0,
        "image_url": "https://tse2.mm.bing.net/th/id/OIP.j6LEoBhqASpWQv1YYlgbtAHaEo",
        "description": "Canon 7D Mark II — robust DSLR for action photography.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon D3300",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "DSLR",
        "tags": ["dslr", "camera", "nikon"],
        "rent_per_day": 800.0,
        "image_url": "https://tse3.mm.bing.net/th/id/OIP.eamnG8hpgwvNFak5M2zSlQHaHa",
        "description": "Affordable DSLR for beginners and hobbyists.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
]

if __name__ == '__main__':
    upserted = 0
    for p in DSLR_PRODUCTS:
        filt = {"category": p["category"], "subcategory": p["subcategory"], "name": p["name"]}
        update = {"$set": p}
        res = products_col.update_one(filt, update, upsert=True)
        # Note: res.upserted_id is not set when matched existing doc
        upserted += 1
    print(f"Processed {len(DSLR_PRODUCTS)} DSLR product upserts")
