from datetime import datetime
import sys, os

# Ensure project root is on sys.path so relative imports like `models` resolve
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from models.db import products_col

MIRRORLESS_PRODUCTS = [
    {
        "name": "Sony Alpha 7 IV",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sony"],
        "rent_per_day": 2000.0,
        "image_url": "https://images.unsplash.com/photo-1630565046172-a45b756acf0f?w=600&auto=format&fit=crop&q=60",
        "description": "Sony Alpha 7 IV — professional full-frame mirrorless for photography and video.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS R50",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "canon"],
        "rent_per_day": 1600.0,
        "image_url": "https://plus.unsplash.com/premium_photo-1667538961167-2f0ab7a5046e?w=600&auto=format&fit=crop&q=60",
        "description": "Canon EOS R50 — versatile mirrorless with great autofocus.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Fujifilm X-T5",
        "brand": "Fujifilm",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "fujifilm"],
        "rent_per_day": 1800.0,
        "image_url": "https://images.unsplash.com/photo-1611952987537-c1c9c1f4f6a2?w=600&auto=format&fit=crop&q=60",
        "description": "Fujifilm X-T5 — compact mirrorless with excellent color science.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon Z9",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "nikon"],
        "rent_per_day": 2400.0,
        "image_url": "https://images.unsplash.com/photo-1651464654814-3031b30d8a99?w=600&auto=format&fit=crop&q=60",
        "description": "Nikon Z9 — professional full-frame with advanced 8K capabilities.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony ZV-E10",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sony"],
        "rent_per_day": 1200.0,
        "image_url": "https://images.unsplash.com/photo-1731424359375-0ceee30ef813?w=600&auto=format&fit=crop&q=60",
        "description": "Sony ZV-E10 — content creator mirrorless with flip screen.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Panasonic Lumix S5II",
        "brand": "Panasonic",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "panasonic"],
        "rent_per_day": 1700.0,
        "image_url": "https://images.unsplash.com/photo-1697208386304-7129844c5df1?w=600&auto=format&fit=crop&q=60",
        "description": "Panasonic Lumix S5II — affordable full-frame mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Olympus OM System",
        "brand": "Olympus",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "olympus"],
        "rent_per_day": 1100.0,
        "image_url": "https://images.unsplash.com/photo-1723472281045-e926a5ee9929?w=600&auto=format&fit=crop&q=60",
        "description": "Olympus mirrorless — compact APS-C with great stabilization.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sigma fp",
        "brand": "Sigma",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sigma"],
        "rent_per_day": 1400.0,
        "image_url": "https://m.media-amazon.com/images/I/61vuQLaJAdL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sigma fp — compact full-frame mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony Alpha 6700",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sony"],
        "rent_per_day": 1350.0,
        "image_url": "https://m.media-amazon.com/images/I/71gB-5SVNUL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Sony Alpha 6700 — APS-C mirrorless with excellent autofocus.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Canon EOS R6",
        "brand": "Canon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "canon"],
        "rent_per_day": 1900.0,
        "image_url": "https://m.media-amazon.com/images/I/61xMohRsKGL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Canon EOS R6 — pro-level full-frame mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Nikon Z50II",
        "brand": "Nikon",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "nikon"],
        "rent_per_day": 1150.0,
        "image_url": "https://m.media-amazon.com/images/I/71veESr7laL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Nikon Z50II — compact APS-C mirrorless for enthusiasts.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Leica SL2",
        "brand": "Leica",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "leica"],
        "rent_per_day": 3200.0,
        "image_url": "https://m.media-amazon.com/images/I/71JurfqudIL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Leica SL2 — premium full-frame mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Hasselblad X1D II 50C",
        "brand": "Hasselblad",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "hasselblad"],
        "rent_per_day": 4000.0,
        "image_url": "https://m.media-amazon.com/images/I/61nKqwfoZBL._AC_UY327_FMwebp_QL65_.jpg",
        "description": "Hasselblad X1D II — high-end medium format mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Sony ZV-E1",
        "brand": "Sony",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "sony"],
        "rent_per_day": 2100.0,
        "image_url": "https://rukminim2.flixcart.com/image/312/312/ktlu9ow0/dslr-camera/r/y/j/alpha-zv-e10-24-2-megapixel-with-interchangeable-lens-aps-c-original-imag6wxxhxrv9htc.jpeg?q=70",
        "description": "Sony ZV-E1 — full-frame content creator camera.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
    {
        "name": "Blackmagic Pocket Cinema Camera 4K",
        "brand": "Blackmagic",
        "category": "Cameras",
        "subcategory": "Mirrorless",
        "tags": ["mirrorless", "camera", "blackmagic"],
        "rent_per_day": 2500.0,
        "image_url": "https://rukminim2.flixcart.com/image/312/312/xif0q/camera/1/y/b/na-blackmagic-pocket-cinema-camera-4k-mirrorless-blackmagic-original-imahf7zberyhaatm.jpeg?q=70",
        "description": "Blackmagic Pocket Cinema 4K — professional video mirrorless.",
        "available": True,
        "created_at": datetime.utcnow(),
    },
]

if __name__ == '__main__':
    for p in MIRRORLESS_PRODUCTS:
        filt = {"category": p["category"], "subcategory": p["subcategory"], "name": p["name"]}
        update = {"$set": p}
        res = products_col.update_one(filt, update, upsert=True)
    print(f"Processed {len(MIRRORLESS_PRODUCTS)} Mirrorless product upserts")
